### ISSUE TITLE
Dynamic DOM Support?

### ISSUE THREAD

**Issue by dr0id123** [amerkurev/scrapper#11]
I've noticed this application is not processing (output) dynamic DOM, and therefore is not compatible with such sites.  For example:

https://angular.io/about?group=Angular

Raw HTML -> Cannot find the word "puppies"
Fully generated DOM (DOM created in the browser, e.g., Chome Dev Tools), -> You can search and find the word "puppies".

Headless browsers should be able to output dynamic DOM as html (e.g., selenium does this).

Am I missing something? It should be possible given real browsers are being used.

**Comment by dr0id123** [comment]
Nevermind, got this sorted -- need to use the correct wait function for all the javascript to process.

**Comment by edwardsmoses** [comment]
> Nevermind, got this sorted -- need to use the correct wait function for all the javascript to process.

Please, could you share which wait function you used? I'm trying to do the same. Thanks.
