### ISSUE TITLE
Thx a lot / ask feature login

### ISSUE THREAD

**Issue by didlawowo** [amerkurev/scrapper#13]
Thx for your little project,
its very nice and powerfull

i'm using it to get article from my medium account

i have also made a recent image with all dependency updated if you need it 

do you think it's possible to add header to make authentification for medium, using email password?

**Comment by amerkurev** [comment]
@didlawowo, you can add headers for authentication using the "extra-http-headers" parameter as described in the documentation. Example: `extra-http-headers: X-Email:user@example.com;X-Password:yourpassword`.
