### ISSUE TITLE
How can I set name of Crawler?

### ISSUE THREAD

**Issue by changingmission** [amerkurev/scrapper#15]
is there any way I can set my crawler name/desc etc.?

**Comment by amerkurev** [comment]
@changingmission sorry, I don't understand what you mean by "set name of crawler." Can you explain it to me in more detail?

**Comment by changingmission** [comment]
Like google crawler use name : Googlebot

**Comment by changingmission** [comment]
@amerkurev is there any way? can I set crawler name?

**Comment by amerkurev** [comment]
@changingmission you can add header for this using the "extra-http-headers" parameter as described in the documentation. Example: extra-http-headers: User-Agent:Googlebot-Image/1.0.
