### ISSUE TITLE
Proposal: Add --user-scripts-timeout parameter to allow a long-running async tasks to success.

### ISSUE THREAD

**Issue by question44** [amerkurev/scrapper#2]
I have a user script injected into the page that often lasts about 3 seconds. Because of that I am unable to get page content successfully.

**Comment by question44** [comment]
I have created a PR: https://github.com/amerkurev/scrapper/pull/3

**Comment by amerkurev** [comment]
Thank you for your participation in the project, I accepted your PR, and put together a new version with your edits already!

**Comment by amerkurev** [comment]
[v0.12.0](https://github.com/amerkurev/scrapper/releases/tag/v0.12.0)
